# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'AppnKzGDH.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import icons_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(902, 705)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet(u"#MainWindow{background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(53, 211, 255, 255), stop:1 rgba(0, 73, 95, 255));}")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy1)
        self.centralwidget.setStyleSheet(u"#centralwidget{background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(53, 211, 255, 255), stop:1 rgba(0, 73, 95, 255));}")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 90, 190, 471))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(5, 100, 181, 40))
        font = QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_2.setAlignment(Qt.AlignCenter)
        self.pushButton_2 = QPushButton(self.frame)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(45, 200, 100, 40))
        icon = QIcon()
        icon.addFile(u":/icons/icons/log-in.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_3 = QPushButton(self.frame)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(45, 300, 100, 40))
        self.pushButton_3.setMouseTracking(False)
        self.pushButton_3.setTabletTracking(True)
        icon1 = QIcon()
        icon1.addFile(u":/icons/icons/codesandbox.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(210, 100, 681, 601))
        font1 = QFont()
        font1.setKerning(True)
        self.frame_2.setFont(font1)
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.stackedWidget = QStackedWidget(self.frame_2)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(50, 30, 560, 511))
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.label_3 = QLabel(self.page)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(50, 50, 131, 25))
        font2 = QFont()
        font2.setPointSize(12)
        font2.setBold(True)
        font2.setWeight(75)
        self.label_3.setFont(font2)
        self.label_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_4 = QLabel(self.page)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(120, 110, 191, 25))
        font3 = QFont()
        font3.setPointSize(10)
        self.label_4.setFont(font3)
        self.label_4.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_5 = QLabel(self.page)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(120, 140, 101, 25))
        self.label_5.setFont(font3)
        self.label_5.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_14 = QLabel(self.page)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(120, 170, 101, 25))
        self.label_14.setFont(font3)
        self.label_14.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_16 = QLabel(self.page)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(120, 200, 131, 25))
        self.label_16.setFont(font3)
        self.label_16.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_17 = QLabel(self.page)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(40, 450, 250, 25))
        font4 = QFont()
        font4.setPointSize(10)
        font4.setItalic(True)
        self.label_17.setFont(font4)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.lineEdit_4 = QLineEdit(self.page_2)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(250, 175, 150, 25))
        self.lineEdit_4.setEchoMode(QLineEdit.Password)
        self.lineEdit_5 = QLineEdit(self.page_2)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(250, 100, 250, 25))
        self.label_6 = QLabel(self.page_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(100, 100, 71, 25))
        self.label_6.setFont(font3)
        self.label_7 = QLabel(self.page_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(100, 175, 81, 25))
        self.label_7.setFont(font3)
        self.pushButton_10 = QPushButton(self.page_2)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(145, 290, 120, 40))
        self.pushButton_10.setMinimumSize(QSize(120, 40))
        self.pushButton_10.setMaximumSize(QSize(120, 40))
        font5 = QFont()
        font5.setPointSize(9)
        self.pushButton_10.setFont(font5)
        icon2 = QIcon()
        icon2.addFile(u":/icons/icons/repeat.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_10.setIcon(icon2)
        self.pushButton_11 = QPushButton(self.page_2)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(320, 290, 120, 40))
        self.pushButton_11.setMinimumSize(QSize(120, 40))
        self.pushButton_11.setMaximumSize(QSize(120, 40))
        self.pushButton_11.setFont(font5)
        self.pushButton_11.setMouseTracking(True)
        icon3 = QIcon()
        icon3.addFile(u":/icons/icons/chevrons-right.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_11.setIcon(icon3)
        self.label_15 = QLabel(self.page_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(50, 40, 201, 30))
        self.label_15.setFont(font)
        self.label_15.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.pushButton_5 = QPushButton(self.page_3)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(230, 400, 100, 45))
        self.pushButton_5.setFont(font3)
        self.pushButton_5.setMouseTracking(True)
        self.pushButton_5.setLayoutDirection(Qt.RightToLeft)
        icon4 = QIcon()
        icon4.addFile(u":/icons/icons/video.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.label_8 = QLabel(self.page_3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(50, 50, 131, 16))
        font6 = QFont()
        font6.setPointSize(12)
        self.label_8.setFont(font6)
        self.label_8.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_9 = QLabel(self.page_3)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(50, 150, 341, 25))
        self.label_9.setFont(font3)
        self.label_9.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_10 = QLabel(self.page_3)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(50, 100, 491, 25))
        self.label_10.setFont(font3)
        self.label_10.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_11 = QLabel(self.page_3)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(50, 200, 411, 25))
        self.label_11.setFont(font3)
        self.label_11.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_12 = QLabel(self.page_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(400, 420, 150, 75))
        self.label_12.setFont(font6)
        self.label_12.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_12.setAlignment(Qt.AlignCenter)
        self.pushButton = QPushButton(self.page_3)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(20, 460, 100, 28))
        self.pushButton.setLayoutDirection(Qt.LeftToRight)
        icon5 = QIcon()
        icon5.addFile(u":/icons/icons/log-out.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton.setIcon(icon5)
        self.lineEdit = QLineEdit(self.page_3)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(50, 360, 400, 25))
        self.label_18 = QLabel(self.page_3)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(50, 260, 201, 16))
        self.label_18.setFont(font3)
        self.label_19 = QLabel(self.page_3)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(50, 290, 111, 25))
        self.label_19.setFont(font3)
        self.label_19.setStyleSheet(u"color: rgb(229, 255, 244);")
        self.label_20 = QLabel(self.page_3)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(50, 320, 321, 25))
        self.label_20.setFont(font3)
        self.label_20.setStyleSheet(u"color: rgb(229, 255, 244);")
        self.stackedWidget.addWidget(self.page_3)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(20, 675, 101, 21))
        font7 = QFont()
        font7.setPointSize(9)
        font7.setItalic(True)
        self.label_13.setFont(font7)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(170, 10, 561, 61))
        font8 = QFont()
        font8.setPointSize(21)
        self.label.setFont(font8)
        self.label.setStyleSheet(u"color:rgb(255, 255, 255)")
        self.label.setAlignment(Qt.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u">>MENU<<", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Log In", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Status", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Project By- ", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"1] Prajali (Leader)", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"2] Anand", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"3] Kishori", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"4] Aishwarya", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Click on the Log In to proceed", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"User", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Password", None))
        self.pushButton_10.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.pushButton_11.setText(QCoreApplication.translate("MainWindow", u"Log In", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"#Admin Log In", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"START  ", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Instructions:", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u">> Press START to start the detection", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u">> Make sure the camera is facing towards the subject correctly", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u">> Press ENTER key to Exit out of the Detection", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"THANK YOU!!!!", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Log Out", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Put the RTSP link here:", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"For Example:", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"rtsp://192.168.137.69:8554/mjpeg/1", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Version 1.08", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Driver Drowsiness Detection System", None))
    # retranslateUi

